### PR TITLE
Update .gitattributes after TravisCI -> GH

### PR DESCRIPTION
**Pull request by williamdes**
Could you make a release for this change please ?

### CODE REVIEW

**Comment by williamdes** [comment]
Hi @DASPRiD 

I reverted one of my previous changes about tests, I hope you do not mind :)

**Comment by DASPRiD** [comment]
No, the Debian distribution package requires the tests to be included. On May 29, 2023 10:36, William Desportes ***@***.***> wrote:Could you make a release for this change please ?



You can view, comment on, or merge this pull request online at:
  https://github.com/DASPRiD/Enum/pull/14

Commit Summary
b143c6e  Update .gitattributes after TravisCI -> GH

File Changes  (1 file)

    M
    .gitattributes
    (2)
  

Patch Links:
https://github.com/DASPRiD/Enum/pull/14.patchhttps://github.com/DASPRiD/Enum/pull/14.diff

**Comment by williamdes** [comment]
Hi @DASPRiD
I am the one doing the packaging et Debian
So you can merge this request, I can get them with some king of magic git clone to archive process with the uscan person program

**Comment by VincentLanglet** [comment]
This would be great to avoid downloading tests files when installing this lib with composer :)

**Comment by williamdes** [comment]
@DASPRiD can you merge this one please?

**Pull request merged**
